import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:rangrej_fleet/core/themes/app_theme.dart';
import 'package:rangrej_fleet/shared/helpers/ui_helper.dart';
import 'package:rangrej_fleet/shared/widgets/common_widgets.dart';
import 'package:rangrej_fleet/shared/views/main_layout.dart';

class CompanyEarningsScreen extends StatefulWidget {
  const CompanyEarningsScreen({super.key});

  @override
  State<CompanyEarningsScreen> createState() => _CompanyEarningsScreenState();
}

class _CompanyEarningsScreenState extends State<CompanyEarningsScreen> {
  DateTime _currentDate = DateTime.now();
  final _revenueController = TextEditingController();
  
  double _totalDriverPayouts = 40600.0; // Mock total driver payouts for the week
  double _companyRevenue = 0.0;
  bool _isSaved = false;
  bool _isLoading = false;

  final _currencyFormat = NumberFormat.currency(locale: 'en_IN', symbol: '₹');

  DateTime get _weekStart {
    int daysToSubtract = _currentDate.weekday - 1;
    return _currentDate.subtract(Duration(days: daysToSubtract));
  }

  DateTime get _weekEnd {
    return _weekStart.add(const Duration(days: 6));
  }

  String get _weekPeriodStr {
    final startFormat = DateFormat('MMM dd');
    final endFormat = DateFormat('MMM dd, yyyy');
    return '${startFormat.format(_weekStart)} - ${endFormat.format(_weekEnd)}';
  }

  double get _ownerShare => _companyRevenue - _totalDriverPayouts;

  bool get _isValid => _companyRevenue > 0 && _companyRevenue >= _totalDriverPayouts && !_isSaved;

  @override
  void initState() {
    super.initState();
    _revenueController.addListener(() {
      setState(() {
        _companyRevenue = double.tryParse(_revenueController.text) ?? 0.0;
      });
    });
  }

  @override
  void dispose() {
    _revenueController.dispose();
    super.dispose();
  }

  void _previousWeek() {
    setState(() {
      _currentDate = _currentDate.subtract(const Duration(days: 7));
      _resetDataForNewWeek();
    });
  }

  void _nextWeek() {
    setState(() {
      _currentDate = _currentDate.add(const Duration(days: 7));
      _resetDataForNewWeek();
    });
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _currentDate,
      firstDate: DateTime(2020),
      lastDate: DateTime(2030),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: AppColors.primary,
              onPrimary: AppColors.white,
              onSurface: AppColors.textPrimary,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() {
        _currentDate = picked;
        _resetDataForNewWeek();
      });
    }
  }

  void _resetDataForNewWeek() {
    // Mock logic: randomly decide if it's saved or not based on week
    _revenueController.clear();
    _companyRevenue = 0.0;
    _isSaved = _currentDate.isBefore(DateTime.now().subtract(const Duration(days: 7)));
    
    if (_isSaved) {
      _companyRevenue = 60000.0;
      _revenueController.text = '60000';
    }
  }

  void _onSave() {
    setState(() => _isLoading = true);
    
    Future.delayed(const Duration(seconds: 1), () {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _isSaved = true;
        });
        UIHelper.showSuccessSnackBar(context, 'Company earnings saved successfully!');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text('Company Earnings'),
        leading: Builder(
          builder: (context) => IconButton(
            icon: context.canPop() ? const Icon(Icons.arrow_back) : const Icon(Icons.menu),
            onPressed: () {
              if (context.canPop()) {
                context.pop();
              } else {
                MainLayout.scaffoldKey.currentState?.openDrawer();
              }
            },
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppDimensions.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            _buildWeekSelector(),
            const SizedBox(height: AppDimensions.lg),
            
            Text('Driver Payouts Summary', style: AppTextStyles.heading2),
            const SizedBox(height: AppDimensions.md),
            
            _buildSummaryCard(),
            const SizedBox(height: AppDimensions.xl),
            
            Text('Enter the gross revenue generated by the entire fleet before any deductions or driver splits.', 
                style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondary)),
            const SizedBox(height: AppDimensions.md),
            
            _buildRevenueInput(),
            const SizedBox(height: AppDimensions.xl),
            
            if (_companyRevenue > 0) ...[
              Text('Calculation Result', style: AppTextStyles.heading2),
              const SizedBox(height: AppDimensions.md),
              _buildCalculationCard(),
              const SizedBox(height: AppDimensions.md),
              Center(
                child: Text(
                  '"Ensuring transparency and fair payouts for every mile driven."',
                  style: AppTextStyles.caption.copyWith(fontStyle: FontStyle.italic, color: AppColors.primary),
                  textAlign: TextAlign.center,
                ),
              ),
              const SizedBox(height: AppDimensions.xl),
            ],
            
            ElevatedButton(
              onPressed: _isValid && !_isLoading ? _onSave : null,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: AppColors.white,
                padding: const EdgeInsets.symmetric(vertical: AppDimensions.md),
              ),
              child: _isLoading
                  ? const SizedBox(
                      height: 22, width: 22,
                      child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.white),
                    )
                  : const Text('Save Earnings'),
            ),
            const SizedBox(height: AppDimensions.xl),
          ],
        ),
      ),
    );
  }

  Widget _buildWeekSelector() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: AppDimensions.md, vertical: AppDimensions.sm),
      decoration: BoxDecoration(
        color: AppColors.white,
        borderRadius: BorderRadius.circular(AppDimensions.radiusLg),
        border: Border.all(color: AppColors.grey200),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            icon: const Icon(Icons.chevron_left, color: AppColors.primary),
            onPressed: _previousWeek,
          ),
          Column(
            children: [
              Text('Weekly Earnings Period', style: AppTextStyles.caption.copyWith(color: AppColors.textSecondary)),
              const SizedBox(height: 4),
              InkWell(
                onTap: _selectDate,
                child: Row(
                  children: [
                    Text(_weekPeriodStr, style: AppTextStyles.labelLarge),
                    const Icon(Icons.arrow_drop_down, color: AppColors.primary),
                  ],
                ),
              ),
            ],
          ),
          IconButton(
            icon: const Icon(Icons.chevron_right, color: AppColors.primary),
            onPressed: _nextWeek,
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryCard() {
    return AppCard(
      padding: const EdgeInsets.all(AppDimensions.lg),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Total Payouts', style: AppTextStyles.labelLarge),
              Text('₹ 1,42,850.00', style: AppTextStyles.heading2.copyWith(color: AppColors.error)),
            ],
          ),
          const Divider(height: 32),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Active Drivers', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondary)),
              Text('24', style: AppTextStyles.labelLarge),
            ],
          ),
          const SizedBox(height: AppDimensions.sm),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Completed Trips', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondary)),
              Text('312', style: AppTextStyles.labelLarge),
            ],
          ),
          const SizedBox(height: AppDimensions.sm),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Estimated Operating Costs', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondary)),
              Text('₹ 28,400.00', style: AppTextStyles.labelLarge.copyWith(color: AppColors.warning)),
            ],
          ),
          const SizedBox(height: 4),
          Text('Based on active fleet logs', style: AppTextStyles.caption.copyWith(color: AppColors.grey400)),
        ],
      ),
    );
  }

  Widget _buildRevenueInput() {
    return AppCard(
      padding: const EdgeInsets.all(AppDimensions.md),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Gross Fleet Revenue', style: AppTextStyles.labelLarge),
          const SizedBox(height: AppDimensions.sm),
          TextField(
            controller: _revenueController,
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            style: AppTextStyles.heading2.copyWith(color: AppColors.primary),
            decoration: InputDecoration(
              prefixText: '₹ ',
              prefixStyle: AppTextStyles.heading2.copyWith(color: AppColors.primary),
              hintText: '0.00',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppDimensions.radiusMd),
                borderSide: BorderSide(color: AppColors.grey200),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppDimensions.radiusMd),
                borderSide: BorderSide(color: AppColors.grey200),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppDimensions.radiusMd),
                borderSide: const BorderSide(color: AppColors.primary, width: 2),
              ),
              filled: true,
              fillColor: AppColors.white,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCalculationCard() {
    // We override the local vars to match the stitch mockup if a value is typed.
    double payouts = 142850.0;
    double opsCost = 28400.0;
    double ownerShare = _companyRevenue - payouts - opsCost;
    
    return Container(
      padding: const EdgeInsets.all(AppDimensions.lg),
      decoration: BoxDecoration(
        color: AppColors.primary,
        borderRadius: BorderRadius.circular(AppDimensions.radiusLg),
        boxShadow: [
          BoxShadow(
            color: AppColors.primary.withOpacity(0.3),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Text('Owner\'s Net Share', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.white.withOpacity(0.9))),
          const SizedBox(height: AppDimensions.sm),
          Text(
            _currencyFormat.format(ownerShare > 0 ? ownerShare : 0),
            style: AppTextStyles.heading1.copyWith(color: AppColors.white),
          ),
        ],
      ),
    );
  }
}
